### ISSUE TITLE
Logging in on the admin panel makes it impossible to perform a POST request from the FE

### ISSUE THREAD

**Issue by Zelzahn** [SELab-2/OSOC-5#153]
This is because the admin panel still works with a CSRF token and this cookie is then set on the localhost domain. Thus this issue is possibly not present on production.

**Comment by Wouter01** [comment]
This issue is present on the production server and is probably linked to #195

**Comment by henricattoire** [comment]
This issue is `wontfix` as authentication for the admin panel and frontend are seperated and have no way of communicating with each other. This just means that it is not possible to login to the frontend when you already logged in using the admin panel. 

One annoying bug is if you logged in using the frontend first, you can still log in using the admin panel. Doing this will prevent the frontend from doing POST, PUT and delete requests until you logged out the admin panel.
